Importing the libraries

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
data_set = pd.read_csv('Dataset/Covid.csv')
x = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

In [47]:
data_set

age body_temperature chronic_disease breathing_issue  \
0   10.0           Normal              no              no   
1   12.0           Normal              no              no   
2   15.0           Normal              no              no   
3   10.0           Normal              no              no   
4   13.0         Moderate              no              no   
..   ...              ...             ...             ...   
65  86.0             High              no             yes   
66  61.0         Moderate              no             yes   
67  94.0             High             yes             yes   
68  81.0             High             yes             yes   
69  76.0             High             yes             yes   

    Blood O2 Level in Percentage Needed Hospitalization  
0                           97.0                     No  
1                           97.0                     No  
2                           94.0                     No  
3                           97.0                     No  
4                           94.0                     No  
..                           ...                    ...  
65                          76.0                    Yes  
66                          90.0                     No  
67                          64.0                    Yes  
68                          75.0                    Yes  
69                          80.0                    Yes  

[70 rows x 6 columns]

In [40]:
print(x)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [41]:
print(y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [42]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 0:1])
x[: , 0:1] = imputer.transform(x[:, 0:1])
imputer.fit(x[:, 4:5])
x[: , 4:5] = imputer.transform(x[:, 4:5])

In [43]:
x

array([[10.0, 'Normal', 'no', 'no', 97.0],
       [12.0, 'Normal', 'no', 'no', 97.0],
       [15.0, 'Normal', 'no', 'no', 94.0],
       [10.0, 'Normal', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 94.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 93.0],
       [15.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 66.0],
       [19.0, 'Normal', 'no', 'no', 92.0],
       [20.0, 'Normal', 'no', 'no', 93.0],
       [17.0, 'Normal', 'no', 'no', 93.0],
       [16.0, 'Normal', 'no', 'no', 92.0],
       [18.0, 'Normal', 'no', 'no', 93.0],
       [20.0, 'Normal', 'no', 'no', 92.0],
       [25.0, 'Moderate', 'no', 'no', 93.0],
       [24.0, 'Moderate', 'no', 'no', 92.0],
       [26.0, 'High', 'no', 'no', 94.0],
       [28.0, 'Normal', 'no', 'no', 99.0],
       [29.0, 'Normal', 'no', 'no', 93.0],
       [30.0, 'Moderate', 'no', 'no', 62.0],
       [19.0, 'Normal', 'no', 'no', 89.0],
       [25.0, 'Normal', 'no', 'yes', 86.

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [45]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder() , [1])] ,remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [46]:
x

array([[0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [0.0, 0.0, 1.0, 15.0, 'no', 'no', 94.0],
       [0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 13.0, 'no', 'no', 94.0],
       [0.0, 1.0, 0.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 13.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 15.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 18.0, 'no', 'no', 66.0],
       [0.0, 0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [0.0, 0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [0.0, 0.0, 1.0, 17.0, 'no', 'no', 93.0],
       [0.0, 0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [0.0, 0.0, 1.0, 18.0, 'no', 'no', 93.0],
       [0.0, 0.0, 1.0, 20.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 25.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 24.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 26.0, 'no', 'no', 94.0],
       [0.0, 0.0, 1.0, 28.0, 'no', 'no', 99.0],
       [0.0, 0.0, 1.0, 29.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 30.0, 'no', 'no',

In [48]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
y = l.fit_transform(y)


In [49]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1])

In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42) 

In [51]:
print(x_train)

[[1.0 0.0 0.0 86.0 'yes' 'yes' 71.0]
 [0.0 1.0 0.0 35.0 'no' 'yes' 92.0]
 [1.0 0.0 0.0 75.0 'no' 'yes' 72.0]
 [1.0 0.0 0.0 42.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 74.0 'yes' 'yes' 75.0]
 [1.0 0.0 0.0 62.0 'yes' 'yes' 68.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 48.0 'no' 'yes' 93.0]
 [1.0 0.0 0.0 58.0 'no' 'no' 70.0]
 [0.0 1.0 0.0 45.130434782608695 'yes' 'no' 90.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 70.0 'no' 'yes' 88.0]
 [1.0 0.0 0.0 52.0 'yes' 'yes' 80.0]
 [1.0 0.0 0.0 60.0 'yes' 'yes' 68.0]
 [1.0 0.0 0.0 54.0 'yes' 'yes' 70.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 78.0 'yes' 'yes' 71.0]
 [1.0 0.0 0.0 36.0 'yes' 'no' 90.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [1.0 0.0 0.0 50.0 'yes' 'yes' 77.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 69.0 'no' 'yes' 53.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [1.0 0.0 0.0 62.0 'yes' 'yes' 69.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 4

In [52]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
x_train[:, 6:] = s.fit_transform(x_train[:, 6:])
x_test[:, 6:] = s.fit_transform(x_test[:,6:])

x_train[:, 3:4] = s.fit_transform(x_train[:, 3:4])
x_test[:, 3:4] = s.fit_transform(x_test[:, 3:4])


In [54]:
print(x_train)

[[1.0 0.0 0.0 1.660595032652111 'yes' 'yes' -0.9941858494300261]
 [0.0 1.0 0.0 -0.5372483818439074 'no' 'yes' 0.9574354145081887]
 [1.0 0.0 0.0 1.1865503746235582 'no' 'yes' -0.9012515035282064]
 [1.0 0.0 0.0 -0.23558359946210095 'no' 'no' 0.9574354145081887]
 [1.0 0.0 0.0 1.1434554057118715 'yes' 'yes' -0.6224484658227472]
 [1.0 0.0 0.0 0.6263157787716318 'yes' 'yes' -1.2729888871354853]
 [0.0 1.0 0.0 -1.0112930398724604 'no' 'no' 0.9574354145081887]
 [0.0 1.0 0.0 0.022986214008018892 'no' 'yes' 1.0503697604100084]
 [1.0 0.0 0.0 0.4539359031248853 'no' 'no' -1.087120195331846]
 [0.0 1.0 0.0 -0.10067760982551668 'yes' 'no' 0.7715667227045492]
 [0.0 1.0 0.0 -1.39914776007764 'no' 'no' 0.9574354145081887]
 [0.0 0.0 1.0 0.9710755300651249 'no' 'yes' 0.5856980309009097]
 [1.0 0.0 0.0 0.19536608965476546 'yes' 'yes' -0.15777673631364833]
 [1.0 0.0 0.0 0.5401258409482586 'yes' 'yes' -1.2729888871354853]
 [1.0 0.0 0.0 0.28155602747813874 'yes' 'yes' -1.087120195331846]
 [0.0 0.0 1.0 -0.795818